Bl 637 fe combine components into main container
BloomTech-Labs/asylum-rg-fe pull request #19
Opened 2022-07-28 17:31 UTC by Joshmclemore

## Description

Made navigation functional and placed "page not found" components where navigation is not yet possible

#### Video Link

https://www.loom.com/share/da21c0ff7b47423687ddebf587217b9e

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-637

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have removed unnecessary comments/console logs from my code
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] No duplicate code left within changed files
- [x] Size of pull request kept to a minimum
- [x] Pull request description clearly describes changes made & motivations for said changes

2022-07-28 17:46 UTC, attaris978 requested changes
Looks great -- just need to remove those mysteriously-transfered Route components in the items.js file.

2022-07-28 17:46 UTC, attaris978 commented on pull_request_template.md
> +https://bloomtechlabs.atlassian.net/browse/BL-637
Are we supposed to be updating the template every time we submit a pull request? My assumption has been that we leave the template and fill out the form on github for each pull request.

2022-07-28 17:46 UTC, attaris978 commented on src/components/Layout/NavBar.js
> +      defaultOpenKeys={['']}
Setting it to a default closed state -- excellent.

2022-07-28 17:46 UTC, attaris978 commented on src/components/Layout/items.js
> +// links are absolute and will need to be changed if implemented on the main site.
Good insight for those-that-come-after.

2022-07-28 17:46 UTC, attaris978 commented on src/components/Layout/items.js
> +// <Route path="/example-list" component={ExampleListPage} />
These are an accidental paste, I think -- the Routes you removed from the index.jsx file.

2022-07-28 17:46 UTC, attaris978 commented on src/index.jsx
> +            <Route path="/heatmap" component={NotFoundPage} />
I like how this enables future components to be implemented in the menu before being finished -- it makes the site feel more complete without it yet being completed.

2022-07-28 17:51 UTC, attaris978 requested changes
Eek -- also, anything containing JSX should have the extension .jsx instead of .js.

2022-07-28 17:51 UTC, Ricardorouge approved these changes

2022-07-28 18:26 UTC, attaris978 approved these changes
💥

2022-07-28 18:28 UTC, Ricardorouge approved these changes

2022-07-28 18:59 UTC, VWashingtonCoder approved these changes
This looks like a pretty clean link-up for the Navbar. I find it useful that each one is fully linked to its representative webpage as well as the table hookup. The not found page link for the Heatmap is also a nice touch.

2022-07-28 23:43 UTC, merged

2022-10-24 16:56 UTC, AlexiusThomas reviewed
The explanation of the raw data being imported was very clear and well organized.